name: publish-loop-package
on:
  push:
    branches:
      - main
    paths:
      - loop/*
  workflow_dispatch:
    inputs:
      comment:
        description: ''
        required: false
        default: 'manual workflow dispatch trigger'
env:
  TEST_SCRIPT: test-loop.js
  NPM_PACKAGE_PATH: loop
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }} # actions/setup-node@v2 uses NODE_AUTH_TOKEN by default
jobs:
  publish:
    defaults:
      run:
        shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - uses: actions/setup-node@v2 # https://github.com/actions/setup-node/blob/main/action.yml
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install package dependencies
        run: |
          cd $GITHUB_WORKSPACE/$NPM_PACKAGE_PATH
          npm install
      - name: Test package functionality
        run: |
          cd $GITHUB_WORKSPACE/tests
          npm install
          node $TEST_SCRIPT
      - name: Publish package to registry
        run: |
          cd $GITHUB_WORKSPACE/$NPM_PACKAGE_PATH
          npm publish --access public
