name: publish-validation-package
on:
  push:
    branches:
      - main
    paths:
      - validation/*
  workflow_dispatch:
    inputs:
      comment:
        description: ''
        required: false
        default: 'manual workflow dispatch trigger'
env:
  TEST_SCRIPT: test-validation.js
  NPM_DIRECTORY: validation
  NPM_USER: vorprog
  NPM_PACKAGE_PATH: validation
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }} # actions/setup-node@v2 uses NODE_AUTH_TOKEN by default
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd $GITHUB_WORKSPACE/tests
          npm install
          node $TEST_SCRIPT
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd $GITHUB_WORKSPACE/$NPM_PACKAGE_PATH
          npm adduser --scope=@$NPM_USER
          npm publish --access public
