name: publish-validation-package
on:
  push:
    branches:
      - main
    paths:
      - validation/*
  workflow_dispatch:
    inputs:
      target_commit:
        required: false
        default: ${{ github.sha }}
env:
  GIT_BRANCH: ${{ github.ref }}
  COMMIT_SHA: ${{ github.sha }}
  NPM_DIRECTORY: validation
  NPM_USER: vorprog
  NPM_PUBLISH_PATH: validation
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }} # actions/setup-node@v2 uses NODE_AUTH_TOKEN by default
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: echo $GITHUB_WORKSPACE
      - run: ls $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE/tests
      - run: pwd
      - run: ls
      - run: npm install
      - run: node test-validation.js
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: cd $GITHUB_WORKSPACE/$NPM_PUBLISH_PATH
      - run: npm adduser --scope=@$NPM_USER
      - run: npm publish --access public
